From zsh-users-return-4239-mason-zsh=primenet.com.au@sunsite.dk Tue Sep 18 11:29:01 2001
Return-Path: <zsh-users-return-4239-mason-zsh=primenet.com.au@sunsite.dk>
Delivered-To: mason-zsh@primenet.com.au
Received: (qmail 23548 invoked from network); 18 Sep 2001 11:29:01 -0000
Received: from sunsite.dk (130.225.51.30)
  by ns1.primenet.com.au with SMTP; 18 Sep 2001 11:29:01 -0000
Received: (qmail 12692 invoked by alias); 18 Sep 2001 11:28:46 -0000
Mailing-List: contact zsh-users-help@sunsite.dk; run by ezmlm
Precedence: bulk
X-No-Archive: yes
Delivered-To: mailing list zsh-users@sunsite.dk
X-Seq: 4239
Received: (qmail 12679 invoked from network); 18 Sep 2001 11:28:45 -0000
To: zsh-users@sunsite.dk
Subject: Re: trap for EXIT doesn't catch exit? 
In-reply-to: "Michal Vitecek"'s message of "Tue, 18 Sep 2001 13:14:16 +0200."
             <20010918131416.A13937@fuf.sh.cvut.cz> 
Date: Tue, 18 Sep 2001 12:28:10 +0100
Message-ID: <674.1000812490@csr.com>
From: Peter Stephenson <pws@csr.com>

Michal Vitecek wrote:
>  in one of my zsh programs i'm creating a number of temporary files which
>  should be removed when the program execution stops or an error occurs
>  and i call 'exit'.
> 
>  however after having specified 'trap CleanUp EXIT' the clean-up
>  function is not called when 'exit' inside a function is executed.
>
>  an example program (test.sh):
>  ----start----
>     #!/bin/zsh
> 
>     function CleanUp()
>     {
> 	  rm -f tempfile
>     } 
> 
>     function WillExit()
>     {
> 	  exit
>     }
> 
> 
>     trap CleanUp EXIT
>     touch tempfile
>     WillExit
>  ----end----
> 
>  $ chmod +x test.sh
>  $ ./test.sh
>  $ ls tempfile
>  tempfile
>  $

Yes, that certainly looks like a bug.

What's happening is this: when you enter the function WillExit, it saves
the trap for exiting the shell and resets the trap, so that if you set a
trap for EXIT it applies on to the function, not the shell.  Usually it
would restore this when the function exits.  However, when you call `exit',
it simply exits the shell without exiting the function scope.  So it never
sees the trap EXIT set for exiting the shell.

Probably the correct thing to do here is to pop all the saved EXIT's off
the stack of saved traps, executing them one by one, to simulate exiting
the scope of each function in turn.  I'll wait to see if there are comments
before I do that (further discussion should probably go to zsh-workers).

A temporary workaround is to install `trap CleanUp Exit' inside WillExit.

-- 
Peter Stephenson <pws@csr.com>                  Software Engineer
CSR Ltd., Science Park, Milton Road,
Cambridge, CB4 0WH, UK                          Tel: +44 (0)1223 392070


**********************************************************************
The information transmitted is intended only for the person or
entity to which it is addressed and may contain confidential 
and/or privileged material. 
Any review, retransmission, dissemination or other use of, or
taking of any action in reliance upon, this information by 
persons or entities other than the intended recipient is 
prohibited.  
If you received this in error, please contact the sender and 
delete the material from any computer.
**********************************************************************

